name: JAVA-CI

on:
  workflow_dispatch:
  push:
    branches:
      master
    tags:
      - 'java-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: "pwd"
      - run: "ls"
      - name: swich path
        run: "cd /home/runner/work/Live-test2/Live-test2/guard"

      - run: "pwd"

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build
          gradle-version: 8.0.2
          build-root-directory: guard
          
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          
      - run: "ls guard/"
      - run: "ls guard/build/"
      - run: "ls guard/build/libs/"

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          file: ./guard/Dockerfile
          context: ./guard
          push: true
          tags: hoi4tech/live-java:latest
