name: WEB-CI

on:
  workflow_dispatch:
  push:
    branches:
      master
    tags:
      - 'web-*'
      
defaults:
  run:
    working-directory: ./chatgpt-web

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          run_install: true

      - name: build
        run: pnpm build
